### ISSUE TITLE
Support URL in import

### ISSUE THREAD

**Issue by devd** [carlinyuen/ChromeAutoTextExpander#12]
It would be nice if I could have a webpage from which replacements are sync'ed and downloaded. The current import flow requires user to copy/paste the JSON file; instead, if I could just provide a URL that is checked on startup and updated, that would be really great!

**Comment by carlinyuen** [comment]
Hi @devd, the shortcuts are actually supposed to be sync'd to Chrome's sync storage, so in theory they should actually sync across browsers you log into. Due to some people putting in seriously large lists of shortcuts and expansions, simply using a URL doesn't work unless I want to start exposing a server where people can send their shortcuts and then generate a short link for them or something. Unfortunately, there's probably not a great workaround for this without potentially compromising security of the extension. :o\

**Comment by carlinyuen** [comment]
Hey @devd going to close this issue if you don't have other ideas around how to support this feature request!

**Comment by devd** [comment]
sounds good, unfortunately

**Comment by carlinyuen** [comment]
Yeah sorry friend, but maybe Chrome will expose better APIs for this one day!
