### ISSUE TITLE
handling leading and trailing spaces

### ISSUE THREAD

**Issue by sygi** [carlinyuen/ChromeAutoTextExpander#14]
_I am describing why do I need leading and trailing spaces in the shortcuts below (please don't judge me!)_.

So, first of all thanks for the plugin, it's going to be a useful thing for me ;)
But, I have a problem with handling leading and trailing spaces:
1. when I create a shortcut with a trailing space (extending to a string with a trailing space as well), it is recognized, but, depending on the type of the field I'm writing in, it is replaced by the string with or without the trailing space. Similar behavior is in the demo fields: Editable Div don't add extra space (giving me 1 space, which I inserted), but Textarea adds an extra space anyway.
2. when I create a shortcut with a leading space, it is not recognized at all, I guess because of the special handling of the space character.

I would be glad to try to resolve the issue myself, with some guidance about where to search for this problem.

My use case is as follows:
I often write in Polish, which uses diacritics (non-latin characters). Usually I just write the words changing Polish chars to their corresponding latin ones (because it's faster), e.g. `mój -> moj`. What I'd like to use your plugin for is to add the Polish characters where it is clear that the word I thought about is the one with diacritics. So, e.g. I write `moj` and get `mój`.
But the problem is that words are sometimes substrings of other words, e.g. there's a word in Polish: `moja` (which doesn't have diacritics). So I want system to add diacritics only to the whole words. I thought creating shortcuts with spaces (and possibly dots/colons) will resolve the issue, but apparently spaces are treated somehow specially.

Thanks for your help

**Comment by carlinyuen** [comment]
Hey Jakub,

Interesting... yes you are correct that unfortunately we use the space
character as a delimiter of sorts for clearing the shortcut keystroke
buffer. However, using dots and colons should work? I do think your point
about the inconsistent handling of trailing spaces should be resolved,
because that's not great when it has confusing behavior. Let me look into
that or feel free to submit a pull request for handling the trailing space!
Unfortunately, I don't think there's much we can do about the leading one
for the time being. :o(


*. Carlin*
............................................
Product . Design . Development
e : email.me@carlinyuen.com
# : +1 (234) 567-9763

**Comment by carlinyuen** [comment]
Hey Jakub, I put in a fix to make the leading space handling more consistent! Check it out and let me know if you still have issues there.
