### ISSUE TITLE
Extension moved from Chrome Store

### ISSUE THREAD

**Issue by nograsswillgrow** [carlinyuen/ChromeAutoTextExpander#56]
Apologies if this isn't the best place to report this, but it seems this extension was removed from the Chrome Store: https://chrome.google.com/webstore/detail/auto-text-expander-for-go/iibninhmiggehlcdolcilmhacighjamp?hl=en-US

Is there any chance this will return in the future? This tool is an excellent part of my workflow now, so I'll definitely miss it if it's now gone!

**Comment by manmoser** [comment]
It now seems to be available under a new name and publisher: "Auto Text Expander 2 for Google Chrome" at the URL https://chrome.google.com/webstore/detail/auto-text-expander-2-for/oclakfhhfnbdmmlgncmfnndhlofgnmpm

**Comment by Will-Low** [comment]
@carlinyuen would you be able to clarify why this has been removed from the Chrome Store? I have reservations about trusting a republishing of this application.

**Comment by carlinyuen** [comment]
Sigh, sorry folks, been really swamped with work and such so haven't paid much attention here. :(

So I dug through my email and found out that it was taken down by the Google Web Store for some policy violation. I think it might have to do with the fact that it uses "Google Chrome" in the title. Bleh.

I've been doing poorly with testing the latest 2.0 version of the extension, so the codebase is in a bit of a tricky state, sorry peeps. :( I could republish the previous version of the extension with a modified name and see if they'll take it. Wdyt?

The current problem is that with v2.0 I think there are some regressions introduced for some of the supported sites (which might be evidenced by complaints people are posting on that separately published extension), but I just need to get around to testing it all before pushing it out.

See below for the email I received:
"Dear Developer,

We have not received an update from you on your Google Chrome item, "Auto Text Expander for Google Chrome™," with ID: iibninhmiggehlcdolcilmhacighjamp, item before the expiry of the warning period specified in our earlier email. Because your item continues to not comply with our policies stated in the previous email, it has now been removed from the Google Chrome Web Store.

If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal. Please keep in mind that your re-submitted item will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published if the item passes review. Important Note: Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform. This may also result in the suspension of related Google services associated with your Google account.

Thank you for your cooperation,

Google Chrome Web Store team"

**Comment by nograsswillgrow** [comment]
@carlinyuen, considering I’ve been using the older version of the extension, I’d love this. A lot of my co-workers actually use this extension as well, so it’d be awesome if it could make its way back in the store. Thanks for all of the info here!

**Comment by Will-Low** [comment]
I'd agree that I think it'd be a good idea to republish the last known working version of the app. Seems like it has a pretty solid user base and I think all would prefer the release come from you yourself, instead of an unknown entity.

**Comment by carlinyuen** [comment]
FYI I've resubmitted the extension to the store with a modified description
with the hope they will republish. Fingers crossed!

.C

**Comment by nograsswillgrow** [comment]
Looks like it got all republished, so this is resolved on my end. Thanks so much, @carlinyuen!

**Comment by carlinyuen** [comment]
👍
